export const mockProfiles = [
  {
    id: 1,
    name: "Arika Gibson",
    role: "Developer",
    year: "2026",
    major: "CS",
    bio: "Full-stack developer passionate about building scalable applications.",
    email: "arika.gibson@example.com",
    avatarUrl: "https://ui-avatars.com/api/?name=Arika+Gibson&background=6B7A3A&color=fff&size=200",
    status: "active",
    isFeatured: true,
  },
  {
    id: 2,
    name: "Julian Luz",
    role: "Designer",
    year: "2025",
    major: "Graphic Design",
    bio: "Creative designer with a passion for user experience and visual aesthetics.",
    email: "julian.luzadder@example.com",
    avatarUrl: "https://ui-avatars.com/api/?name=Julian+Luzadder&background=2E5090&color=fff&size=200",
    status: "active",
    isFeatured: true,
  },
  {
    id: 3,
    name: "Lyndie Lingg",
    role: "Product Manager",
    year: "2024",
    major: "Business",
    bio: "Strategic thinker focused on creating products that solve real problems.",
    email: "lyndie.lingg@example.com",
    avatarUrl: "https://ui-avatars.com/api/?name=Lyndie+Lingg&background=C4453C&color=fff&size=200",
    status: "active",
    isFeatured: true,
  },
];
